solution
javastartbootcamp/jjd-ind-58_PawelMaliszewski_zad_9.2 pull request #1
Opened 2023-03-19 17:23 UTC by PawelMaliszewski

2023-03-19 19:15 UTC, slawekludwiczak requested changes
code review https://javastartbootcamp.slack.com/archives/C04CJF5PV0U/p1679253328890669

2023-03-19 19:15 UTC, slawekludwiczak commented on src/main/java/pl/javastart/task/vehicle/VehicleUtils.java
> +            if (vehicle.getId() == name) {
Stringi powinny być porównywane przez metodę equals()

2023-03-19 19:15 UTC, slawekludwiczak commented on src/main/java/pl/javastart/task/vehicle/VehicleUtils.java
> +    }
W tych metodach możesz wywołać showSpecificCarInfo()

2023-03-19 19:15 UTC, slawekludwiczak commented on src/main/java/pl/javastart/task/vehicle/Vehicle.java
> +    }
Ta metoda powinna być dopiero w klasie Car

2023-03-19 19:15 UTC, slawekludwiczak commented on src/main/java/pl/javastart/task/vehicle/Car.java
> +    }
Obliczanie zasięgu zarówno tutaj, jak i później w Truck można uprościć. Pokazane w code review

2023-03-19 19:15 UTC, slawekludwiczak commented on src/main/java/pl/javastart/task/vehicle/Car.java
> +    private final double airConConsumption = .8;
Stałe nazywamy wielkimi literami

2023-03-19 19:15 UTC, slawekludwiczak commented on src/main/java/pl/javastart/task/vehicle/Car.java
> +        return rangeWithAirConOff() * 100;
Jeżeli w Truck masz 100 zdefiniowaną jako stałą, to tutaj też przydałaby się konsekwencja

2023-03-20 09:19 UTC, slawekludwiczak requested changes
code review https://javastartbootcamp.slack.com/archives/C04CJF5PV0U/p1679303940629299

2023-03-20 09:19 UTC, slawekludwiczak commented on src/main/java/pl/javastart/task/vehicle/Truck.java
> +        return  (tankDividedByFuelConsumption() + weightFuelConsumption()) * BY_100_KM;
Ten if nie jest potrzebny. Jeżeli. ładunek będzie 0, to metoda `weightFuelConsumption()` zwróci 0 i też będzie ok

2023-03-20 09:19 UTC, slawekludwiczak commented on src/main/java/pl/javastart/task/vehicle/Truck.java
> +    }
Stałe i ogólnie składowe statyczne nie podlegają polimorfizmowi, polimorficzne są tylko metody, dlatego musiałeś nadpisać metodę.

Gdybyś połączył metody weightFuelConsumption i getCurrentFuelConsumption (albo wykorzystał weightFuelConsumption w getCurrentFuelConsumption), czyli metoda getCurrentFuelConsumption zwracałaby spalanie z uwzględnieniem klimatyzacji i załadunku, to nie musiałbyś w tej klasie wcale zapisywać metody range(), bo tak jak wspominałem w poprzednim code review sam wzór na zasięg jest zawsze identyczny, czyli ilość_paliwa/spalanie*100, niezależnie od tego o jakim pojeździe mówimy

2023-03-20 09:20 UTC, slawekludwiczak requested changes

2023-03-20 09:20 UTC, slawekludwiczak commented on src/main/java/pl/javastart/task/vehicle/Vehicle.java
> +    }
Ta metoda może zwracać tankCapacity/averageFuelConsumption, albo najlepiej tak jak pokazałem w code review możesz tutaj stworzyć metodę np. getCurrentConsumption() i to będzie jedyna metoda nadpisywana w klasach pochodnych

2023-03-23 10:58 UTC, marcinkunert approved these changes

2023-11-21 07:16 UTC, closed without merging